version: "3.9"
services:
  database:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nest_app
    depends_on:
      - database
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "3000:3000"
    command: ["npm", "run", "start:dev"]

volumes:
  postgres_data:
